@startuml

abstract class AbstractList
abstract class AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|-- List
AbstractCollection <|-- AbstractList
AbstractList <|-- ArrayList

class ArrayList{
   Object[] elementData
   size()
}
enum TimeUnit{
  DAYS
  HOURS
  MINITES
}

@enduml